AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
TARGET_COLUMN: price
DROP_COLUMN: ['id']
TEST_TRAIN_SPLIT: 0.4
RANDOM_STATE: 42