artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file_train: artifacts/data_ingestion/train.csv.zip
  local_data_file_test: artifacts/data_ingestion/test.csv.zip
  unzip_dir: artifacts/data_ingestion



prepare_base_model:
  data_dir: artifacts\data_ingestion\train.csv
  root_dir: artifacts/prepare_base_model
  model_param_file : artifacts/prepare_base_model/model_params.json
  base_model_path: artifacts/prepare_base_model/models
  updated_base_model_path: artifacts/prepare_base_model/




prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/